import type { ReactElement } from 'react'
import Head from 'next/head'
import { AuthLayout } from 'layouts/AuthLayout'

export default function MultimediaPage () {
  return (
    <div>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='w-full h-full'>
        <span>LCP Admin - Multimedia</span>
        <br />
        <span>data</span>
      </div>
    </div>
  )
}

MultimediaPage.getLayout = (page: ReactElement) =>
<AuthLayout>
  <Head>
    <title>Multimedia - LCP Admin</title>
  </Head>

  {page}
</AuthLayout>
